// <auto-generated />
namespace AssClassLibrary.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class myMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(myMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201308140604258_myMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
